export const ADD_BUN = 'ADD_BUN';
export const REMOVE_BUN = 'REMOVE_BUN';
export const ADD_MAIN_AND_SAUCE = 'ADD_MAIN_AND_SAUCE';
export const REMOVE_MAIN_AND_SAUCE = 'REMOVE_MAIN_AND_SAUCE';
export const CALCULATE_TOTAL = 'CALCULATE_TOTAL';
